# Generated by Django 4.2.2 on 2023-06-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0002_employee_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to='coffees.location'),
            preserve_default=False,
        ),
    ]
