# Generated by Django 4.2.2 on 2023-06-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0004_alter_employee_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to='coffees.location'),
        ),
    ]
