# Generated by Django 4.2.2 on 2023-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0005_alter_employee_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coffees',
            field=models.ManyToManyField(blank=True, related_name='coffees', to='coffees.coffee'),
        ),
    ]
